name: QuickBuild v4.5 20241220

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Quick Build
    steps:
    - name: Checkout project and transforms
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Build Packages
#      run: "sudo apt-get update && sudo apt-get install -y xsltproc hunspell pandoc"
      run: "sudo apt-get update && sudo apt-get install -y xsltproc hunspell python3-lxml"

    - name: Install Jing
      run: wget -O - https://github.com/relaxng/jing-trang/releases/download/V20181222/jing-20181222.zip | jar -x

    - name: Set branch name
      run: echo "action_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Set base URL
      run: echo "action_projname=${PWD##*/}" >> $GITHUB_ENV
      
    - name: Spew
      run: make inter && cp abc.xml output
        
    - name:  Prepare checkout
      run: |
        mkdir gh-pages

    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

        
    - name:  Move output to branch
      run: |
        rm -rf gh-pages/${{ env.action_branch }}
        mv output gh-pages/${{ env.action_branch }}
        echo moved to gh-pages/${{ env.action_branch }}
        
    - name: Make listing
      run: |
        cd gh-pages
        (echo "<html><head><title>Listing</title></head><body>";
         date;
         echo "<br/><ol>";
         for aa in $(find . -name '*.*'); do
            echo "<li><a href='$aa'>$aa</a></li>";
         done;
         echo "</ol></body></html>") > index.html
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: gh-pages # The folder the action should deploy.
