# This is a the Common Criteria build workflow that is triggered on push

name: SanityChecks

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-project:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout project and transforms
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Build Packages
        run: sudo apt-get update && sudo apt-get install -y xsltproc
 
      - name: Generate Warnings
        run: make output/SanityChecksOutput.md && cat output/SanityChecksOutput.md

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.

      - name: Check warnings
        run: "[ ! -s output/SanityChecksOutput.md ]"

